Minimaxの実装
takasyo/quarto pull request #9
Opened 2020-03-18 10:16 UTC by takasyo

#3 
αβ法は使ってないので計算量が多い
よって10手目以降にMinimax実行するプログラム
また，評価値の計算が単純すぎるのでよっぽどのことがない限り左上に置きがち

2020-03-18 10:51 UTC, takasyo commented on Player.py
> +        """
https://note.nkmk.me/python-docstring/

2020-03-19 19:58 UTC, NB29979 requested changes
特にminimax()等アルゴリズムの詳細はまだ深く見ていないけどざっとコード見て気になったところコメントしました

対応よろしく

2020-03-19 19:58 UTC, NB29979 commented on Player.py
> +            field_status = copy.deepcopy(_field_status)
インスタンス変数からメソッド内変数にしたのは良い変更だと思います 👍

2020-03-19 19:58 UTC, NB29979 commented on Player.py
> +                if field_status[search_index] == '':
ここのIsEmpty()をわざわざ==''にする意図があれば教えてください

2020-03-19 19:58 UTC, NB29979 commented on Player.py
> +            self.npc_turn = _turn % 2 + 1
self.npc_turnはここ以外ではminimax()でしか使っていないので，minimax()の引数で_turnを持たせてminimax()内でnpc_turnと16-_turnさせた方が良いんじゃないだろうか 💡 

minimax()はその実引数が16-_turnで，仮引数が_turnなのも揺れているのでコードの大規模化に伴ってミスを引き起こしそう

2020-03-19 19:58 UTC, NB29979 commented on Player.py
> +
copy.deepcopy()は重複しているのでcopied_available_piecesとか直前につくってまとめるとか 🙃

2020-03-19 19:58 UTC, NB29979 commented on Player.py
> +        """
docstringいいけどなぜこのメソッドだけなのか…？ 🤔

2020-03-19 19:58 UTC, NB29979 commented on Player.py
> +        win = 5
変数winは定数ですか？定数なら大文字にするとか，1文字にするとかありそう
winだと勝利数の印象（勝利数を表していたとしてもwin_count等が適切）

2020-03-19 19:58 UTC, NB29979 commented on quarto.py
数字よりもわかりやすくてよい！ 👍

2020-03-19 19:58 UTC, NB29979 commented on quarto.py
>                      else:
ムダにわかりにくいリスト内包表記をわかりやすくしてくれたのは良いと思います 💡

2020-03-20 05:33 UTC, takasyo commented on Player.py
> +        """
quarto.pyのgameIsOver()と違ってPlayer.pyはGameOverTypeだけ返すので自分が見てわかりやすいように書きました

2020-03-20 05:39 UTC, takasyo commented on Player.py
> +                if field_status[search_index] == '':
selectQuartoSlotIndex()は引数にfield_statusを追加したのでfield_statusの空白をチェックするためです．selectedSlotIsEmpty()だとFieldInfo.field_statusの空白をチェックするので望んだ結果が得られません

2020-03-20 05:46 UTC, takasyo commented on Player.py
> +
対応します

2020-03-20 05:48 UTC, takasyo commented on Player.py
> +        win = 5
calc_score()はまたこれから練っていきますが，とりあえずwinは定数として扱っているので大文字にします

2020-03-20 09:26 UTC, takasyo commented on Player.py
> +            self.npc_turn = _turn % 2 + 1
minimaxの中で_turnが絡む計算は全部16-_turnでやった方がいいということでしょうか？
のちに先攻後攻を選べるようにする場合(#8 )，引数の_turnだけではnpc_turnなのかどうかが分からなくなるのでminimax()が最初に呼ばれる前にnpc_turnを宣言してます

2020-03-20 18:16 UTC, NB29979 commented on Player.py
> +                if field_status[search_index] == '':
深いコピーした方のfield_statusの状態を調べるために代えた感じか～

使用箇所が今回は限られるから対応は任せますが==''よりも.isEmpty()の方が可読性は向上するので今後心掛けてみて！

2020-03-20 18:26 UTC, NB29979 commented on Player.py
> +            self.npc_turn = _turn % 2 + 1
よく考えたらminimax()再帰関数だからminimax()内で16-_turnはまずそう
現在の引数に渡す際に16-_turnで大丈夫だと思います

2020-03-20 18:38 UTC, NB29979 commented on Player.py
> +            self.npc_turn = _turn % 2 + 1
ただ101行目のminimax()の実引数は'16-_turn'という引数に関わらず，minimax()の仮引数がそもそも_turnなので，可読性が低い．

メソッド呼出時を主にするのか，メソッド内を主にするのかを明確にした方が良く思います．
メソッド呼出時を主にするなら
`best = self.minimax(_given_piece, available_pieces, field_status, 16-present_turn)`とか
メソッド内を主にするなら
` def minimax(self, _given_piece, _available_pieces, _field_status, _current_turn):`
引数ごとの揺れに対応する．

2020-03-20 18:43 UTC, NB29979 commented on Player.py
> +            self.npc_turn = _turn % 2 + 1
`self.npc_turn`についてはよくわかりました．
しかし先攻/後攻についてのメンバ変数はインスタンス生成時に決定できる要素では？ 🤔

2020-03-21 04:11 UTC, takasyo commented on Player.py
> +                if field_status[search_index] == '':
了解です！！

2020-03-21 04:23 UTC, takasyo commented on Player.py
> +            self.npc_turn = _turn % 2 + 1
>先攻/後攻についてのメンバ変数はインスタンス生成時に決定できる要素では？

→確かにそうですね！その場合，npc_turnを引数でもってこなければいけませんね．
>minimax()の実引数は'16-_turn'という引数に関わらず，minimax()の仮引数がそもそも_turnなので，可読性が低い．

→minimax()の実引数をすべて_turnにして，153行目の`if _turn == 0`を`if _turn == 16`に変更して対応します！

2020-04-07 13:37 UTC, NB29979 approved these changes
レビュー遅れてすみません～
多少コメントしました

確認よろしくお願いします
Playerクラスがかなり肥大化しているので分割するとか必要だと思います

2020-04-07 13:37 UTC, NB29979 commented on Player.py
> +                    best[2] = score
scoreがもつ意味の制限よき 👍

2020-04-07 13:37 UTC, NB29979 commented on quarto.py
>          for i in range(16):
ここからのコメントは可能であればコミットログに残さないほうがよい

2020-04-07 13:39 UTC, NB29979 commented
プログラムが大規模化してきたのでUML書いて整理するとかするとよいかもね

2020-04-07 13:44 UTC, takasyo commented
UMLって金田先生がやってたやつですよね
 ぜんぜん分からないまま単位もらってもーたんやー:-1:

2020-04-07 15:32 UTC, NB29979 commented
そこまで対したもの描かなくてもどこでインスタンスになっているかとかどこで継承されているかとか大体のクラス間の関係などが明記できれば見通しがだいぶ良くなるのでオススメです
https://www.google.co.jp/search?q=how+to+design+uml&ie=UTF-8&oe=

マークアップ言語で書くのも実はサービスとして既にあってPlant UMLなどあります
https://qiita.com/couzie/items/9dedb834c5aff09ea7b2

まあ最初から大したものはできないさ

2020-04-09 09:15 UTC, merged